version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: your-project-name
    ports:
      - "8001:8000"  # ローカルのポート8001をコンテナのポート8000にマッピング
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
